---
- name: localhost testing
  hosts: localhost
  gather_facts: False
  tasks:
    - name: find files in tmp
      find:
        paths: /tmp/ssh
        patterns: "*"
      register: tmpfiles

    - debug:
        msg: "{{ tmpfiles }}"

- name: testing
  hosts: test
  remote_user: default
  become: False
  gather_facts: True
  tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname] }}"



  
