---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: test
      labels:
        app: playbook2image-example
    spec:
      containers:
      - name: test 
        image: 172.30.7.246:5000/playbook2image-ex/test
        env:
        - name: INVENTORY_FILE
          value: "/opt/app-root/src/hosts.ini"
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        - name: PLAYBOOK_FILE
          value: "/opt/app-root/src/main.yml"
        - name: ANSIBLE_PRIVATE_KEY_FILE 
          value: /opt/app-root/src/.ssh/id_rsa
        - name: ANSIBLE_LOCAL_TEMP
          value: /tmp/ansible-temp
        - name: SSH_KEY
          value: /tmp/foo
        volumeMounts:
        - name: sshkey
          mountPath: /opt/app-root/src/.ssh
      restartPolicy: Never


